before_install:
  - if [[ `gem -v` != 1.8.* ]]; then gem update --system; fi
script: "script/test_all && bin/rake cucumber --trace 2>&1"
bundler_args: "--binstubs"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby
