before_install:
  - if [[ `gem -v` != 1.8.* ]]; then gem update --system; fi
script: "script/test_all 2>&1"
bundler_args: "--standalone --binstubs"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 2.0.0
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rbx-19mode
    - rbx-18mode

